### ISSUE TITLE
Siaf aperture definition error for NRCA1_GRISMTS

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/pysiaf#92] opened 2019-07-22 18:43 UTC
I've come across what I think is an error in the aperture definitions for the NRCA1_GRISMTS apertures. The `parent_apertures` for these cases appear to be incorrect. Below is an example of the problem I am seeing:

```
import pysiaf
from pysiaf import iando
siaf = pysiaf.Siaf('nircam')
aperture = 'NRCA1_GRISMTS128'
aperture_check = siaf[aperture]
siaf_aperture_definitions = iando.read.read_siaf_aperture_definitions('nircam')
index = siaf_aperture_definitions['AperName'].tolist().index(aperture)
aperture_check._parent_apertures = siaf_aperture_definitions['parent_apertures'][index]
print(aperture_check._parent_apertures)
>   'NRCA1_FULL; NRCA5_GRISM128_F444W'
```
When I run the case above using the NRCA3_GRISMTS128 aperture, the parent aperture is `NRCA3_FULL`, as expected. Perhaps the semi-colon after NRCA1_FULL is the problem? I see the same error for all 3 of the NRCA1_GRISMTS apertures.

**Comment by Johannes-Sahlmann** [comment] 2019-08-05 18:08
Thank you for reporting this.

These dependencies were implemented with @marthaboyer recently and I believe they work as intended, see https://jira.stsci.edu/browse/JWSTSIAF-129
Can you please clarify whether this actually throws/causes an error somewhere in your code?

**Comment by marthaboyer** [comment] 2019-08-05 22:24
I get the following when I enter the same commands: 

 from pysiaf import iando
 siaf = pysiaf.Siaf('nircam')
 aperture = 'NRCA1_GRISMTS128'
 aperture_check = siaf[aperture]
 siaf_aperture_definitions = iando.read.read_siaf_aperture_definitions('nircam')
 index = siaf_aperture_definitions['AperName'].tolist().index(aperture)
 aperture_check._parent_apertures = siaf_aperture_definitions['parent_apertures'][index]
 print(aperture_check._parent_apertures)
 >  NRCA1_FULL

????

**Comment by Johannes-Sahlmann** [comment] 2019-08-06 13:19
@marthaboyer you may be running an outdated version. what is the output of `print(pysiaf.__version__ )`

**Comment by bhilbert4** [comment] 2019-08-06 14:21
This didn't cause an error in my code other than that I was expecting a single aperture as the `_parent_apertures` value. Easy enough to work around.

**Comment by Johannes-Sahlmann** [comment] 2019-08-06 15:02
OK. I will close this issue then. 
Within pysiaf, the parent_apertures attribute is being used during the generation of the SIAF and not otherwise.

**Closed by Johannes-Sahlmann** 2019-08-06 15:02 UTC
